const candidates=[
["c01","Backend specialist","Senior backend engineer · deep systems · no AI"],["c02","AI product engineer","Hands-on product + engineering · strong LLM evidence"],["c03","Senior product manager","Strong product ownership · little coding"],["c04","Technical PM","APIs, platforms and data · moderate hands-on depth"],["c05","Junior full-stack","Early career · broad implementation evidence"],["c06","Forward deployed engineer","Customer-facing engineering · deployments and integrations"],["c07","Ambiguous hybrid","Product, engineering and customer work are evenly mixed"],["c08","AI product manager","Strong AI product work · limited implementation"],["c09","Staff engineer","Deep architecture and technical leadership · no product ownership"],["c10","Founder-builder","0→1 product ownership · hands-on full-stack"],["c11","Data / ML engineer","Production ML systems · limited product leadership"],["c12","Operations PM","Workflow ownership · integrations · low engineering evidence"]];
const labels={jev:"Jev 1.13",openai:"GPT-5.6 Luna",openrouter:"OpenRouter · free"};
const sampleResume=c=>`${c[1].toUpperCase()} — SYNTHETIC RESUME\n\n${c[2]}\n\nThis preview will be replaced by the complete fixture content used by the runner.\nThe exact same input is sent to every selected model.`;
const list=document.querySelector("#candidateList"),name=document.querySelector("#candidateName"),desc=document.querySelector("#candidateDescription"),preview=document.querySelector("#inputPreview"),comparison=document.querySelector("#comparison");
let active=candidates[0][0];
const selectedProviders=()=>[...document.querySelectorAll("[data-provider]:checked")].map(x=>x.dataset.provider);
function renderCandidates(){list.innerHTML="";for(const c of candidates){const b=document.createElement("button");b.className="candidate "+(active===c[0]?"active":"");b.innerHTML=`<span>${c[0].slice(1)}</span><div><strong>${c[1]}</strong><small>${c[2]}</small></div>`;b.onclick=()=>{active=c[0];renderCandidates();renderCandidate()};list.append(b)}}
function providerColumn(p){return `<section class="providerColumn"><div class="providerHead"><span class="eyebrow">MODEL</span><h4>${labels[p]}</h4></div><article class="decision"><span class="type">SCORE</span><h5>technical_depth</h5><div class="placeholder">Score + distribution</div></article><article class="decision"><span class="type">CHOICE</span><h5>primary_profile</h5><div class="placeholder">Choice + probabilities</div></article><article class="decision"><span class="type">NOUL</span><h5>llm_experience</h5><div class="placeholder">True / false probability</div></article><div class="metrics"><span>Latency <b>—</b></span><span>Input <b>—</b></span><span>Output <b>—</b></span></div></section>`}
function renderCandidate(){const c=candidates.find(x=>x[0]===active);name.textContent=c[1];desc.textContent=c[2];preview.textContent=sampleResume(c);comparison.innerHTML=selectedProviders().map(providerColumn).join("")}
function renderConfig(){const ps=selectedProviders();document.querySelector("#modelSummary").textContent=`${ps.length} model${ps.length===1?"":"s"}`;document.querySelector("#evalSummary").textContent=`${12*ps.length} evaluations`;renderCandidate()}
function loadHistory(){try{return JSON.parse(localStorage.getItem("jev-lab:runs")||"[]")}catch{return[]}}
function renderHistory(){const runs=loadHistory(),el=document.querySelector("#historyList");el.innerHTML=runs.length?runs.map(r=>`<div class="historyRow"><div><strong>${new Date(r.createdAt).toLocaleString()}</strong><span>${r.candidates} candidates · ${r.providers.map(p=>labels[p]).join(" + ")}</span></div><code>${r.id}</code></div>`).join(""):`<div class="placeholder">No saved runs yet. Runs are stored in this browser.</div>`}
function saveRun(providers){const runs=loadHistory();runs.unshift({id:crypto.randomUUID(),createdAt:new Date().toISOString(),providers,candidates:candidates.length,status:"prepared"});localStorage.setItem("jev-lab:runs",JSON.stringify(runs.slice(0,100)));renderHistory()}
document.querySelectorAll("[data-provider]").forEach(x=>x.addEventListener("change",renderConfig));
document.querySelector("#advancedToggle").onclick=()=>document.querySelector("#advanced").classList.toggle("hidden");
document.querySelector("#viewInput").onclick=()=>preview.classList.toggle("hidden");
document.querySelector("#clearHistory").onclick=()=>{localStorage.removeItem("jev-lab:runs");renderHistory()};
document.querySelector("#run").onclick=async()=>{const notice=document.querySelector("#notice"),ps=selectedProviders();notice.classList.remove("hidden");notice.textContent="Checking configured API keys…";const r=await fetch("/api/status"),s=await r.json(),missing=[];for(const p of ps){if(p==="jev"&&!s.typesafeKeyConfigured)missing.push("TYPESAFE_API_KEY");if(p==="openai"&&!s.openaiKeyConfigured)missing.push("OPENAI_API_KEY");if(p==="openrouter"&&!s.openrouterKeyConfigured)missing.push("OPENROUTER_API_KEY")}if(missing.length){notice.textContent=`Missing: ${missing.join(", ")}`;return}saveRun(ps);notice.textContent="Run saved locally. Live provider execution is the next integration step.";document.querySelector("#resultStatus").textContent="Prepared"};
renderCandidates();renderConfig();renderHistory();