let candidates=[];
const labels={jev:"Jev 1.13",openai:"GPT-5.6 Luna",openrouter:"OpenRouter · free"},storageKey="jev-lab:runs";
const sampleResume=c=>c[3]||"";
const list=document.querySelector("#candidateList"),name=document.querySelector("#candidateName"),desc=document.querySelector("#candidateDescription"),preview=document.querySelector("#inputPreview"),comparison=document.querySelector("#comparison"),picker=document.querySelector("#runPicker");
let active=candidates[0][0],hydratedRun=null;
const loadHistory=()=>{try{return JSON.parse(localStorage.getItem(storageKey)||"[]")}catch{return[]}};
const selectedProviders=()=>hydratedRun?hydratedRun.providers:[...document.querySelectorAll("[data-provider]:checked")].map(x=>x.dataset.provider);
function setProviderChecks(ps){document.querySelectorAll("[data-provider]").forEach(x=>x.checked=ps.includes(x.dataset.provider))}
function renderCandidates(){list.innerHTML="";for(const c of candidates){const b=document.createElement("button");b.className="candidate "+(active===c[0]?"active":"");b.innerHTML=`<span>${c[0].slice(1)}</span><div><strong>${c[1]}</strong><small>${c[2]}</small></div>`;b.onclick=()=>{active=c[0];renderCandidates();renderCandidate()};list.append(b)}}
function providerColumn(p){const saved=hydratedRun?.results?.[active]?.[p];const d=saved?.decisions||{};return `<section class="providerColumn"><div class="providerHead"><span class="eyebrow">MODEL</span><h4>${labels[p]||p}</h4></div><article class="decision"><span class="type">SCORE</span><h5>technical_depth</h5><div class="${d.technical_depth?"result":"placeholder"}">${d.technical_depth?JSON.stringify(d.technical_depth):"Score + distribution"}</div></article><article class="decision"><span class="type">CHOICE</span><h5>primary_profile</h5><div class="${d.primary_profile?"result":"placeholder"}">${d.primary_profile?JSON.stringify(d.primary_profile):"Choice + probabilities"}</div></article><article class="decision"><span class="type">NOUL</span><h5>llm_experience</h5><div class="${d.llm_experience?"result":"placeholder"}">${d.llm_experience?JSON.stringify(d.llm_experience):"True / false probability"}</div></article><div class="metrics"><span>Latency <b>${saved?.latencyMs??"—"}${saved?.latencyMs?" ms":""}</b></span><span>Input <b>${saved?.inputTokens??"—"}</b></span><span>Output <b>${saved?.outputTokens??"—"}</b></span></div></section>`}
function renderCandidate(){const c=candidates.find(x=>x[0]===active);name.textContent=c[1];desc.textContent=c[2];preview.textContent=hydratedRun?.inputs?.[active]||sampleResume(c);comparison.innerHTML=selectedProviders().map(providerColumn).join("")}
function renderConfig(){const ps=selectedProviders();document.querySelector("#modelSummary").textContent=`${ps.length} model${ps.length===1?"":"s"}`;document.querySelector("#evalSummary").textContent=`${12*ps.length} evaluations`;renderCandidate()}
function runLabel(r){return `${new Date(r.createdAt).toLocaleString()} · ${r.providers.map(p=>labels[p]||p).join(" + ")}`}
function renderHistory(){const runs=loadHistory(),el=document.querySelector("#historyList");picker.innerHTML='<option value="">New run</option>'+runs.map(r=>`<option value="${r.id}" ${hydratedRun?.id===r.id?"selected":""}>${runLabel(r)}</option>`).join("");el.innerHTML=runs.length?runs.map(r=>`<button class="historyRow ${hydratedRun?.id===r.id?"active":""}" data-run="${r.id}"><div><strong>${new Date(r.createdAt).toLocaleString()}</strong><span>${r.candidates} candidates · ${r.providers.map(p=>labels[p]||p).join(" + ")}</span></div><code>${r.id.slice(0,8)}</code></button>`).join(""):`<div class="placeholder">No saved runs yet. Runs are stored in this browser.</div>`;el.querySelectorAll("[data-run]").forEach(b=>b.onclick=()=>hydrate(b.dataset.run))}
function hydrate(id){const r=loadHistory().find(x=>x.id===id);if(!r)return;hydratedRun=r;setProviderChecks(r.providers);document.querySelector("#hydratedBanner").classList.remove("hidden");document.querySelector("#hydratedLabel").textContent=runLabel(r);document.querySelector("#resultStatus").textContent=r.status==="complete"?"Saved results":"Saved run";document.querySelector("#run").classList.add("hidden");document.querySelector("#advancedToggle").classList.add("hidden");renderConfig();renderHistory()}
function newRun(){hydratedRun=null;document.querySelector("#hydratedBanner").classList.add("hidden");document.querySelector("#run").classList.remove("hidden");document.querySelector("#advancedToggle").classList.remove("hidden");document.querySelector("#resultStatus").textContent="Not run";renderConfig();renderHistory()}
function saveRun(providers){const runs=loadHistory(),inputs=Object.fromEntries(candidates.map(c=>[c[0],sampleResume(c)]));const run={id:crypto.randomUUID(),createdAt:new Date().toISOString(),providers,candidates:candidates.length,status:"prepared",inputs,results:{}};runs.unshift(run);localStorage.setItem(storageKey,JSON.stringify(runs.slice(0,100)));hydrate(run.id)}
document.querySelectorAll("[data-provider]").forEach(x=>x.addEventListener("change",renderConfig));document.querySelector("#advancedToggle").onclick=()=>document.querySelector("#advanced").classList.toggle("hidden");document.querySelector("#viewInput").onclick=()=>preview.classList.toggle("hidden");document.querySelector("#clearHistory").onclick=()=>{localStorage.removeItem(storageKey);newRun()};document.querySelector("#newRun").onclick=newRun;picker.onchange=()=>picker.value?hydrate(picker.value):newRun();
document.querySelector("#run").onclick=async()=>{const notice=document.querySelector("#notice"),ps=selectedProviders();notice.classList.remove("hidden");notice.textContent="Checking configured API keys…";const r=await fetch("/api/status"),s=await r.json(),missing=[];for(const p of ps){if(p==="jev"&&!s.typesafeKeyConfigured)missing.push("TYPESAFE_API_KEY");if(p==="openai"&&!s.openaiKeyConfigured)missing.push("OPENAI_API_KEY");if(p==="openrouter"&&!s.openrouterKeyConfigured)missing.push("OPENROUTER_API_KEY")}if(missing.length){notice.textContent=`Missing: ${missing.join(", ")}`;return}saveRun(ps);notice.textContent="Run snapshot saved locally. Live results will hydrate into this same run record.";};
async function boot(){const r=await fetch("/api/dataset");const d=await r.json();candidates=d.candidates.map(c=>[c.id,c.title,c.description,c.markdown]);active=candidates[0]?.[0];renderCandidates();renderConfig();renderHistory()}boot();